name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create env file
      run: |
          touch .env
          echo PORT=3000 >> .env
          echo SERVER=0.0.0.0 >> .env
          echo GOOGLE_USER=${{ secrets.GOOGLE_USER }} >> .env
          echo GOOGLE_PASS=${{ secrets.GOOGLE_PASS }} >> .env
          echo DB_SERVER=localhost >> .env
          echo DB_PORT=27017 >> .env
          echo secretKey=${{ secrets.SECRET_KEY }} >> .env
          cat .env   
    - name: Start Docker for Mongodb
      run: docker run -d -p 27017:27017 mongo    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
  build-node:
    runs-on: self-hosted
    steps:
      - name: Remove old containers
        run: |
          docker container rm -f express-mongo  
          docker container rm -f mongo      
      - name: Create env file
        run: |
          touch .env
          echo PORT=3001 >> .env
          echo SERVER=0.0.0.0 >> .env
          echo GOOGLE_USER=${{ secrets.GOOGLE_USER }} >> .env
          echo GOOGLE_PASS=${{ secrets.GOOGLE_PASS }} >> .env
          echo DB_SERVER=mongo >> .env
          echo DB_PORT=27017 >> .env
          cat .env   
      - name: run docker compose
        run: docker-compose up --build -d  
        env:
          CD: true
      
