name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: self-hosted
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Create env file
      run: |
          touch .env
          echo PORT=3000 >> .env
          echo SERVER=0.0.0.0 >> .env
          echo GOOGLE_USER=${{ secrets.GOOGLE_USER }} >> .env
          echo GOOGLE_PASS=${{ secrets.GOOGLE_PASS }} >> .env
          echo DB_SERVER=localhost >> .env
          echo DB_PORT=27017 >> .env
          cat .env   
    - name: Start Docker for Mongodb
      run: docker container rm -f mongo && docker run -d -p 27017:27017 mongo    
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true

  build-node:
    runs-on: self-hosted
    steps:
      - name: Remove old containers
        run: |
          docker container rm -f express-mongo  
          docker container rm -f mongo      
      - name: Create env file
        run: |
          touch .env
          echo PORT=3001 >> .env
          echo SERVER=0.0.0.0 >> .env
          echo GOOGLE_USER=${{ secrets.GOOGLE_USER }} >> .env
          echo GOOGLE_PASS=${{ secrets.GOOGLE_PASS }} >> .env
          echo DB_SERVER=mongo >> .env
          echo DB_PORT=27017 >> .env
          cat .env   
      - name: run docker compose
        run: docker-compose up --build -d  
        env:
          CD: true
      
